### This file is generated by SALOME automatically by dump python functionality
### of GEOM component

import geompy
import math
import SALOMEDS

def RebuildData(theStudy):
	geompy.init_geom(theStudy)
	global B_1, Surface, L8, C_1, D, Line_5, Line_8, L9, L1, Line_6, Line_9, V2, B, L2, P3_1, C, L3, V1, P1, Line_3, L4, Line_4, D_1, Vertex_1, A_1, P2, L5, Vertex_2, Line_7, Surface_1, Line_1, P1_1, L6, Line_2, P2_1, A, L7, P3
	A = geompy.MakeVertex(0, 0, 0)
	P1 = geompy.MakeVertex(12.5, 0, 0)
	P2 = geompy.MakeVertex(217.5, 0, 0)
	B = geompy.MakeVertex(230, 0, 0)
	C = geompy.MakeVertex(230, 75, 0)
	P3 = geompy.MakeVertex(115, 75, 0)
	D = geompy.MakeVertex(0, 75, 0)
	Line_1 = geompy.MakeLineTwoPnt(A, P1)
	Line_2 = geompy.MakeLineTwoPnt(P1, P2)
	Line_3 = geompy.MakeLineTwoPnt(P2, B)
	Line_4 = geompy.MakeLineTwoPnt(B, C)
	Line_7 = geompy.MakeLineTwoPnt(D, A)
	Vertex_1 = geompy.MakeVertex(12.5, 75, 0)
	Vertex_2 = geompy.MakeVertex(217.5, 75, 0)
	geomObj_1 = geompy.GetSubShape(Line_4, [3])
	geomObj_2 = geompy.GetSubShape(Line_4, [3])
	geomObj_3 = geompy.GetSubShape(Line_4, [3])
	Line_5 = geompy.MakeLineTwoPnt(C, Vertex_2)
	Line_6 = geompy.MakeLineTwoPnt(Vertex_2, P3)
	Line_8 = geompy.MakeLineTwoPnt(P3, Vertex_1)
	Line_9 = geompy.MakeLineTwoPnt(Vertex_1, D)
	Surface = geompy.MakeFaceWires([Line_1, Line_2, Line_3, Line_4, Line_7, Line_5, Line_6, Line_8, Line_9], 1)
	listSubShapeIDs = geompy.SubShapeAllIDs(Surface, geompy.ShapeType["FACE"])
	A_1 = geompy.CreateGroup(Surface, geompy.ShapeType["VERTEX"])
	geompy.UnionIDs(A_1, [7])
	Surface = geompy.GetMainShape(A_1)
	Surface = geompy.GetMainShape(A_1)
	P1_1 = geompy.CreateGroup(Surface, geompy.ShapeType["VERTEX"])
	geompy.UnionIDs(P1_1, [9])
	Surface = geompy.GetMainShape(P1_1)
	Surface = geompy.GetMainShape(P1_1)
	Surface = geompy.GetMainShape(P1_1)
	P2_1 = geompy.CreateGroup(Surface, geompy.ShapeType["VERTEX"])
	geompy.UnionIDs(P2_1, [11])
	Surface = geompy.GetMainShape(P2_1)
	Surface = geompy.GetMainShape(P2_1)
	Surface = geompy.GetMainShape(P2_1)
	B_1 = geompy.CreateGroup(Surface, geompy.ShapeType["VERTEX"])
	geompy.UnionIDs(B_1, [13])
	Surface = geompy.GetMainShape(B_1)
	Surface = geompy.GetMainShape(B_1)
	C_1 = geompy.CreateGroup(Surface, geompy.ShapeType["VERTEX"])
	geompy.UnionIDs(C_1, [15])
	Surface = geompy.GetMainShape(C_1)
	Surface = geompy.GetMainShape(C_1)
	V2 = geompy.CreateGroup(Surface, geompy.ShapeType["VERTEX"])
	geompy.UnionIDs(V2, [17])
	Surface = geompy.GetMainShape(V2)
	Surface = geompy.GetMainShape(V2)
	P3_1 = geompy.CreateGroup(Surface, geompy.ShapeType["VERTEX"])
	geompy.UnionIDs(P3_1, [19])
	Surface = geompy.GetMainShape(P3_1)
	Surface = geompy.GetMainShape(P3_1)
	Surface = geompy.GetMainShape(P3_1)
	V1 = geompy.CreateGroup(Surface, geompy.ShapeType["VERTEX"])
	geompy.UnionIDs(V1, [4])
	Surface = geompy.GetMainShape(V1)
	Surface = geompy.GetMainShape(V1)
	D_1 = geompy.CreateGroup(Surface, geompy.ShapeType["VERTEX"])
	geompy.UnionIDs(D_1, [5])
	Surface = geompy.GetMainShape(D_1)
	Surface = geompy.GetMainShape(D_1)
	Surface_1 = geompy.CreateGroup(Surface, geompy.ShapeType["FACE"])
	geompy.UnionIDs(Surface_1, [1])
	Surface = geompy.GetMainShape(Surface_1)
	Surface = geompy.GetMainShape(Surface_1)
	Surface = geompy.GetMainShape(Surface_1)
	L1 = geompy.CreateGroup(Surface, geompy.ShapeType["EDGE"])
	geompy.UnionIDs(L1, [8])
	Surface = geompy.GetMainShape(L1)
	Surface = geompy.GetMainShape(L1)
	Surface = geompy.GetMainShape(L1)
	L2 = geompy.CreateGroup(Surface, geompy.ShapeType["EDGE"])
	geompy.UnionIDs(L2, [10])
	Surface = geompy.GetMainShape(L2)
	Surface = geompy.GetMainShape(L2)
	Surface = geompy.GetMainShape(L2)
	L3 = geompy.CreateGroup(Surface, geompy.ShapeType["EDGE"])
	geompy.UnionIDs(L3, [12])
	Surface = geompy.GetMainShape(L3)
	Surface = geompy.GetMainShape(L3)
	Surface = geompy.GetMainShape(L3)
	L4 = geompy.CreateGroup(Surface, geompy.ShapeType["EDGE"])
	geompy.UnionIDs(L4, [14])
	Surface = geompy.GetMainShape(L4)
	Surface = geompy.GetMainShape(L4)
	L5 = geompy.CreateGroup(Surface, geompy.ShapeType["EDGE"])
	geompy.UnionIDs(L5, [16])
	Surface = geompy.GetMainShape(L5)
	Surface = geompy.GetMainShape(L5)
	Surface = geompy.GetMainShape(L5)
	L6 = geompy.CreateGroup(Surface, geompy.ShapeType["EDGE"])
	geompy.UnionIDs(L6, [18])
	Surface = geompy.GetMainShape(L6)
	Surface = geompy.GetMainShape(L6)
	Surface = geompy.GetMainShape(L6)
	L7 = geompy.CreateGroup(Surface, geompy.ShapeType["EDGE"])
	geompy.UnionIDs(L7, [20])
	Surface = geompy.GetMainShape(L7)
	Surface = geompy.GetMainShape(L7)
	Surface = geompy.GetMainShape(L7)
	Surface = geompy.GetMainShape(L7)
	L8 = geompy.CreateGroup(Surface, geompy.ShapeType["EDGE"])
	geompy.UnionIDs(L8, [3])
	Surface = geompy.GetMainShape(L8)
	Surface = geompy.GetMainShape(L8)
	Surface = geompy.GetMainShape(L8)
	Surface = geompy.GetMainShape(L8)
	L9 = geompy.CreateGroup(Surface, geompy.ShapeType["EDGE"])
	geompy.UnionIDs(L9, [6])
	Surface = geompy.GetMainShape(L9)
	Surface = geompy.GetMainShape(L9)
	geompy.addToStudy( A, "A" )
	geompy.addToStudy( P1, "P1" )
	geompy.addToStudy( P2, "P2" )
	geompy.addToStudy( B, "B" )
	geompy.addToStudy( C, "C" )
	geompy.addToStudy( P3, "P3" )
	geompy.addToStudy( D, "D" )
	geompy.addToStudy( Line_1, "Line_1" )
	geompy.addToStudy( Line_2, "Line_2" )
	geompy.addToStudy( Line_3, "Line_3" )
	geompy.addToStudy( Line_4, "Line_4" )
	geompy.addToStudy( Vertex_1, "Vertex_1" )
	geompy.addToStudy( Line_7, "Line_7" )
	geompy.addToStudy( Vertex_2, "Vertex_2" )
	geompy.addToStudy( Line_5, "Line_5" )
	geompy.addToStudy( Line_6, "Line_6" )
	geompy.addToStudy( Line_8, "Line_8" )
	geompy.addToStudy( Line_9, "Line_9" )
	geompy.addToStudy( Surface, "Surface" )
	geompy.addToStudyInFather( Surface, A_1, "A" )
	geompy.addToStudyInFather( Surface, P1_1, "P1" )
	geompy.addToStudyInFather( Surface, P2_1, "P2" )
	geompy.addToStudyInFather( Surface, B_1, "B" )
	geompy.addToStudyInFather( Surface, C_1, "C" )
	geompy.addToStudyInFather( Surface, V2, "V2" )
	geompy.addToStudyInFather( Surface, P3_1, "P3" )
	geompy.addToStudyInFather( Surface, V1, "V1" )
	geompy.addToStudyInFather( Surface, D_1, "D" )
	geompy.addToStudyInFather( Surface, Surface_1, "Surface" )
	geompy.addToStudyInFather( Surface, L1, "L1" )
	geompy.addToStudyInFather( Surface, L2, "L2" )
	geompy.addToStudyInFather( Surface, L3, "L3" )
	geompy.addToStudyInFather( Surface, L4, "L4" )
	geompy.addToStudyInFather( Surface, L5, "L5" )
	geompy.addToStudyInFather( Surface, L6, "L6" )
	geompy.addToStudyInFather( Surface, L7, "L7" )
	geompy.addToStudyInFather( Surface, L8, "L8" )
	geompy.addToStudyInFather( Surface, L9, "L9" )
	pass
